version: "3.8"

services:

  database:
    image: postgres:14.9
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: ${DATABASE_PGDATA}
    volumes:
      - ${DATABASE_PGDATA}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    restart: always
    networks:
      - custom
    env_file:
      - .env

  # bot application service
  bot-app:
    build:
      context: ./bot-app
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - database
    restart: always
    networks:
      - custom
    env_file:
      - .env

  # admin application service
  admin-app:
    build:
      context: ./admin
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations 
                  && python manage.py migrate 
                  &&  python manage.py add_superuser 
                  && python manage.py runserver '${ADMIN_SITE_HOST}:${ADMIN_SITE_PORT}'"
    ports:
      - ${ADMIN_SITE_PORT}:${ADMIN_SITE_PORT}
    depends_on:
      - database
    restart: always
    networks:
      - custom
    env_file:
      - .env

networks:
  custom:
    driver: bridge
