# Generated by Django 4.2.5 on 2023-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_date", models.DateField()),
                ("slot_time", models.TimeField()),
                ("is_open", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tickets_slot",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tickets_ticket",
                "managed": False,
            },
        ),
    ]
