# Generated by Django 4.2.5 on 2023-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Button",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=10)),
                ("slug", models.CharField(max_length=20, unique=True)),
                ("message", models.TextField(null=True)),
            ],
            options={
                "db_table": "bot_buttons",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("slug", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "bot_pages",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PagesButtons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "bot_pages_buttons",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
            ],
            options={
                "db_table": "bot_settings",
                "managed": False,
            },
        ),
    ]
