# Generated by Django 4.2.5 on 2023-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("telegram_id", models.PositiveIntegerField()),
                ("telegram_username", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(blank=True, max_length=12, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users_client",
                "managed": False,
            },
        ),
    ]
